# Server Configuration
server:
  port: 8001
  error:
    include-message: always
    include-binding-errors: always

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  cloud:
    config:
      import-check:
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/currency-exchange?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

  liquibase:
    change-log: classpath:./db/changelog/changelog-master.xml

# Google Sheets Configuration
# Application Configuration
application:
  name: googlesheetsDemo

# Google Sheets Configuration
spreadsheet:
  id: 1kF-OFH51mvWd-3Le5or4L7wBubIoHde0nJdqZrUrofc/edit?gid=0#gid=0

credentials:
  file:
    path: ./credentials.json

tokens:
  directory:
    path: tokens
