package com.exchange.currencyexchangebackend.model.enums;

public enum NamePermission {
    ALL, DASHBOARD, NEW_EXCHANGE, EXCHANGE_LIST,FUNDS_MANAGEMENT, LOANS, REPORTS, USER_LIST, USER_ADD, USER_EDIT, USER_DELETE, CURENCY_LIST, CURRENCY_ADD, CURRENCY_EDIT, CURRENCY_DELETE, PERMISSION_LIST, PERMISSION_ADD, PERMISSION_EDIT, PERMISSION_DELETE, ROLE_LIST, ROLE_ADD, ROLE_EDIT, ROLE_DELETE, COMPANY_LIST, COMPANY_ADD, COMPANY_EDIT, COMPANY_DELETE, SETTINGS
}
